name: GoManGoEnterprises
favicon: null
layout_spectrum: 0.5497855641879141
typography_spectrum: 0.10921159130521119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
